use jcers::{JceGet, JcePut};
use bytes::Bytes;

jce_struct!(TroopListRequest {
    0 => uin: i64,
    1 => get_msf_msg_flag: u8,
    2 => cookies: Bytes,
    3 => group_info: Vec<i64>,
    4 => group_flag_ext: u8,
    5 => version: i32,
    6 => company_id: i64,
    7 => version_num: i64,
    8 => get_long_group_name: u8,
});

jce_struct!(TroopNumber {
    0 => group_uin: i64,
    1 => group_code: i64,
    2 => flag: u8,
    3 => group_info_seq: i64,
    4 => group_name: String,
    5 => group_memo: String,
    6 => group_flag_ext: i64,
    7 => group_rank_seq: i64,
    8 => certification_type: i64,
    9 => shut_up_timestamp: i64,
    10 => my_shut_up_timestamp: i64,
    11 => cmd_uin_uin_flag: i64,
    12 => additional_flag: i64,
    13 => group_type_flag: i64,
    14 => group_sec_type: i64,
    15 => group_sec_type_info: i64,
    16 => group_class_ext: i64,
    17 => app_privilege_flag: i64,
    18 => subscription_uin: i64,
    19 => member_num: i64,
    20 => member_num_seq: i64,
    21 => member_card_seq: i64,
    22 => group_flag_ext3: i64,
    23 => group_owner_uin: i64,
    24 => is_conf_group: u8,
    25 => is_modify_conf_group_face: u8,
    26 => is_modify_conf_group_name: u8,
    27 => cmd_uin_join_time: i64,
    28 => company_id: i64,
    29 => max_group_member_num: i64,
    30 => cmd_uin_group_mask: i64,
    31 => guild_app_id: i64,
    32 => guild_sub_type: i64,
    33 => cmd_uin_ringtone_i_d: i64,
    34 => cmd_uin_flag_ex2: i64,
});